{% set name = "pyfd" %}
{% set version = "4.5.9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://software.igwn.org/lscsoft/source/{{ name }}-{{ version }}.tar.gz
  sha256: 77334204f8e07d4d5083bbc61645685840fd6ce5c0408f80bc849ef1415a93fc

build:
  run_exports:
    - {{ pin_subpackage("pyfd", max_pin="x") }}
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake >=3.12.0
    - make  # [unix]
  host:
    - fd >=8.43.7
    - python
    - ctypesgen >=1.0.2
  run:
    - python

test:
  imports:
    - PyFd

about:
  home: https://git.ligo.org/virgo/virgoapp/PyFd
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python binding for the Fd Library

extra:
  recipe-maintainers:
    - rhyspoulton
    - fcarbogn
