schema_version: 1

context:
  version: "4.5.10"
  version_parts: ${{ version | split(".") }}
  virgo_version: "v${{ version_parts[0] }}r${{ version_parts[1] }}p${{ version_parts[2] }}"
  # dependencies
  fd_version: "8.43.7"

package:
  name: pyfd
  version: ${{ version }}

source:
  url: https://git.ligo.org/virgo/virgoapp/PyFd/-/archive/${{ virgo_version }}/PyFd-${{ virgo_version }}.tar.gz
  sha256: a8d0dd593fcd9d850101bddd7226128077973f1f0a3fc03d4b723b66ea27997b
  patches:
    - 0001-Use-IS_WRITABLE-unary-test.patch

build:
  number: 2
  skip: not linux

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cmake >=3.12.0
    - make
    - pkg-config
  host:
    - ctypesgen >=1.0.2
    - fd ${{ fd_version }}.*
    - python
  run:
    - python
  run_exports:
    - ${{ pin_subpackage("pyfd", upper_bound="x") }}

tests:
  - python:
      imports:
        - PyFd

about:
  summary: Python binding for the Fd Library
  homepage: https://git.ligo.org/virgo/virgoapp/PyFd
  repository: https://git.ligo.org/virgo/virgoapp/PyFd.git
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - duncanmmacleod
    - erinelizabethseder-virgo
    - fcarbogn
